# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 37d7ccc47db76aae52ad07a7c4a3e3025358b54dfd92a6d6276a028c2364af23e6b0280ae95a780586df418c00648e465a816254f8722799088da9cb02e5c40e

test:
  secret_key_base: 8b1a6b63f50665d6ce93ae49b752aafcfd3fd969eaa7de906a82f8a065b7cd9da1dc57ec0095d48dccb150f24f49667ae5d898e2e72a07bcc4d8f05c4a22aeb7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
